name: hour_tracker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  event_bloc: ^1.0.0
  event_navigation: ^0.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  provider: ^5.0.0
  search_me_up: ^0.1.1
  tuple: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true